// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: amoled_1p9

#include "../ui.h"

void ui_SetWeightValue_screen_init(void)
{
ui_SetWeightValue = lv_obj_create(NULL);
lv_obj_clear_flag( ui_SetWeightValue, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_SetWeightValue, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SetWeightValue, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ButtonN1 = lv_btn_create(ui_SetWeightValue);
lv_obj_set_width( ui_ButtonN1, 100);
lv_obj_set_height( ui_ButtonN1, 74);
lv_obj_set_x( ui_ButtonN1, 5 );
lv_obj_set_y( ui_ButtonN1, 5 );
lv_obj_add_flag( ui_ButtonN1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonN1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_ButtonN1, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_ButtonN1, lv_color_hex(0x1B1B1B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ButtonN1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label1 = lv_label_create(ui_ButtonN1);
lv_obj_set_width( ui_Label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label1,"1");
lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ButtonN2 = lv_btn_create(ui_SetWeightValue);
lv_obj_set_width( ui_ButtonN2, 100);
lv_obj_set_height( ui_ButtonN2, 74);
lv_obj_set_x( ui_ButtonN2, 110 );
lv_obj_set_y( ui_ButtonN2, 5 );
lv_obj_add_flag( ui_ButtonN2, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonN2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_ButtonN2, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_ButtonN2, lv_color_hex(0x1B1B1B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ButtonN2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label3 = lv_label_create(ui_ButtonN2);
lv_obj_set_width( ui_Label3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label3, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label3,"2");
lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ButtonN3 = lv_btn_create(ui_SetWeightValue);
lv_obj_set_width( ui_ButtonN3, 100);
lv_obj_set_height( ui_ButtonN3, 74);
lv_obj_set_x( ui_ButtonN3, 216 );
lv_obj_set_y( ui_ButtonN3, 5 );
lv_obj_add_flag( ui_ButtonN3, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonN3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_ButtonN3, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_ButtonN3, lv_color_hex(0x1B1B1B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ButtonN3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label18 = lv_label_create(ui_ButtonN3);
lv_obj_set_width( ui_Label18, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label18, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label18, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label18,"3");
lv_obj_set_style_text_font(ui_Label18, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ButtonN4 = lv_btn_create(ui_SetWeightValue);
lv_obj_set_width( ui_ButtonN4, 100);
lv_obj_set_height( ui_ButtonN4, 74);
lv_obj_set_x( ui_ButtonN4, 5 );
lv_obj_set_y( ui_ButtonN4, 83 );
lv_obj_add_flag( ui_ButtonN4, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonN4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_ButtonN4, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_ButtonN4, lv_color_hex(0x1B1B1B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ButtonN4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label19 = lv_label_create(ui_ButtonN4);
lv_obj_set_width( ui_Label19, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label19, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label19, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label19,"4");
lv_obj_set_style_text_font(ui_Label19, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ButtonN5 = lv_btn_create(ui_SetWeightValue);
lv_obj_set_width( ui_ButtonN5, 100);
lv_obj_set_height( ui_ButtonN5, 74);
lv_obj_set_x( ui_ButtonN5, 110 );
lv_obj_set_y( ui_ButtonN5, 83 );
lv_obj_add_flag( ui_ButtonN5, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonN5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_ButtonN5, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_ButtonN5, lv_color_hex(0x1B1B1B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ButtonN5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label20 = lv_label_create(ui_ButtonN5);
lv_obj_set_width( ui_Label20, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label20, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label20, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label20,"5");
lv_obj_set_style_text_font(ui_Label20, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ButtonN6 = lv_btn_create(ui_SetWeightValue);
lv_obj_set_width( ui_ButtonN6, 100);
lv_obj_set_height( ui_ButtonN6, 74);
lv_obj_set_x( ui_ButtonN6, 216 );
lv_obj_set_y( ui_ButtonN6, 83 );
lv_obj_add_flag( ui_ButtonN6, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonN6, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_ButtonN6, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_ButtonN6, lv_color_hex(0x1B1B1B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ButtonN6, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label21 = lv_label_create(ui_ButtonN6);
lv_obj_set_width( ui_Label21, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label21, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label21, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label21,"6");
lv_obj_set_style_text_font(ui_Label21, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ButtonN7 = lv_btn_create(ui_SetWeightValue);
lv_obj_set_width( ui_ButtonN7, 100);
lv_obj_set_height( ui_ButtonN7, 74);
lv_obj_set_x( ui_ButtonN7, 5 );
lv_obj_set_y( ui_ButtonN7, 162 );
lv_obj_add_flag( ui_ButtonN7, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonN7, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_ButtonN7, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_ButtonN7, lv_color_hex(0x1B1B1B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ButtonN7, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label22 = lv_label_create(ui_ButtonN7);
lv_obj_set_width( ui_Label22, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label22, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label22, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label22,"7");
lv_obj_set_style_text_font(ui_Label22, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ButtonN8 = lv_btn_create(ui_SetWeightValue);
lv_obj_set_width( ui_ButtonN8, 100);
lv_obj_set_height( ui_ButtonN8, 74);
lv_obj_set_x( ui_ButtonN8, 110 );
lv_obj_set_y( ui_ButtonN8, 162 );
lv_obj_add_flag( ui_ButtonN8, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonN8, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_ButtonN8, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_ButtonN8, lv_color_hex(0x1B1B1B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ButtonN8, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label23 = lv_label_create(ui_ButtonN8);
lv_obj_set_width( ui_Label23, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label23, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label23, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label23,"8");
lv_obj_set_style_text_font(ui_Label23, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ButtonN9 = lv_btn_create(ui_SetWeightValue);
lv_obj_set_width( ui_ButtonN9, 100);
lv_obj_set_height( ui_ButtonN9, 74);
lv_obj_set_x( ui_ButtonN9, 216 );
lv_obj_set_y( ui_ButtonN9, 162 );
lv_obj_add_flag( ui_ButtonN9, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonN9, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_ButtonN9, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_ButtonN9, lv_color_hex(0x1B1B1B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ButtonN9, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label24 = lv_label_create(ui_ButtonN9);
lv_obj_set_width( ui_Label24, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label24, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label24, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label24,"9");
lv_obj_set_style_text_font(ui_Label24, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ButtonN0 = lv_btn_create(ui_SetWeightValue);
lv_obj_set_width( ui_ButtonN0, 100);
lv_obj_set_height( ui_ButtonN0, 74);
lv_obj_set_x( ui_ButtonN0, 320 );
lv_obj_set_y( ui_ButtonN0, 162 );
lv_obj_add_flag( ui_ButtonN0, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonN0, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_ButtonN0, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_ButtonN0, lv_color_hex(0x1B1B1B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ButtonN0, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label25 = lv_label_create(ui_ButtonN0);
lv_obj_set_width( ui_Label25, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label25, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label25, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label25,"0");
lv_obj_set_style_text_font(ui_Label25, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label26 = lv_label_create(ui_SetWeightValue);
lv_obj_set_width( ui_Label26, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label26, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label26, 159 );
lv_obj_set_y( ui_Label26, -73 );
lv_obj_set_align( ui_Label26, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label26,"120");
lv_obj_set_style_text_font(ui_Label26, &ui_font_RowFont, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ButtonN10 = lv_btn_create(ui_SetWeightValue);
lv_obj_set_width( ui_ButtonN10, 108);
lv_obj_set_height( ui_ButtonN10, 74);
lv_obj_set_x( ui_ButtonN10, 424 );
lv_obj_set_y( ui_ButtonN10, 162 );
lv_obj_add_flag( ui_ButtonN10, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonN10, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_ButtonN10, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_ButtonN10, lv_color_hex(0x1B1B1B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ButtonN10, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label27 = lv_label_create(ui_ButtonN10);
lv_obj_set_width( ui_Label27, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label27, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label27, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label27,"OK");
lv_obj_set_style_text_font(ui_Label27, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ButtonN11 = lv_btn_create(ui_SetWeightValue);
lv_obj_set_width( ui_ButtonN11, 212);
lv_obj_set_height( ui_ButtonN11, 74);
lv_obj_set_x( ui_ButtonN11, 320 );
lv_obj_set_y( ui_ButtonN11, 83 );
lv_obj_add_flag( ui_ButtonN11, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonN11, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_ButtonN11, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_ButtonN11, lv_color_hex(0x1B1B1B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ButtonN11, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label28 = lv_label_create(ui_ButtonN11);
lv_obj_set_width( ui_Label28, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label28, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label28, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label28,"<");
lv_obj_set_style_text_font(ui_Label28, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_SetWeightValue, ui_event_SetWeightValue, LV_EVENT_ALL, NULL);

}
