// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: amoled_1p9

#include "ui.h"

///////////////////// VARIABLES ////////////////////
// default weight unit lb
uint8_t weightUnit = 0;

void weightUnitChange(lv_event_t *e)
{
	// change weight unit
	weightUnit = !weightUnit;
	// update weight unit label
	if (weightUnit)
	{
		lv_label_set_text(ui_WeightUnit, "kg");
	}
	else
	{
		lv_label_set_text(ui_WeightUnit, "lb");
	}
}
