// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: amoled_1p9

#include "../ui.h"

void ui_RowScreen_screen_init(void)
{
ui_RowScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_RowScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Panel3 = lv_obj_create(ui_RowScreen);
lv_obj_set_width( ui_Panel3, 533);
lv_obj_set_height( ui_Panel3, 183);
lv_obj_set_x( ui_Panel3, -1 );
lv_obj_set_y( ui_Panel3, 26 );
lv_obj_set_align( ui_Panel3, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label6 = lv_label_create(ui_Panel3);
lv_obj_set_width( ui_Label6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label6, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label6, 322 );
lv_obj_set_y( ui_Label6, -30 );
lv_obj_set_align( ui_Label6, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_Label6,"average\npower");
lv_obj_set_style_text_font(ui_Label6, &lv_font_montserrat_42, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label5 = lv_label_create(ui_Panel3);
lv_obj_set_width( ui_Label5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label5, 123 );
lv_obj_set_y( ui_Label5, 56 );
lv_obj_set_align( ui_Label5, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_Label5,"gear");
lv_obj_set_style_text_font(ui_Label5, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label9 = lv_label_create(ui_Panel3);
lv_obj_set_width( ui_Label9, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label9, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label9, -189 );
lv_obj_set_y( ui_Label9, -25 );
lv_obj_set_align( ui_Label9, LV_ALIGN_RIGHT_MID );
lv_label_set_text(ui_Label9,"602");
lv_obj_set_style_text_color(ui_Label9, lv_color_hex(0xFF6DF6), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label9, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label9, &ui_font_RowFont2, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label10 = lv_label_create(ui_Panel3);
lv_obj_set_width( ui_Label10, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label10, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label10, -381 );
lv_obj_set_y( ui_Label10, 59 );
lv_obj_set_align( ui_Label10, LV_ALIGN_RIGHT_MID );
lv_label_set_text(ui_Label10,"120");
lv_obj_set_style_text_font(ui_Label10, &ui_font_RowFont, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label13 = lv_label_create(ui_Panel3);
lv_obj_set_width( ui_Label13, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label13, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label13, -104 );
lv_obj_set_y( ui_Label13, 59 );
lv_obj_set_align( ui_Label13, LV_ALIGN_RIGHT_MID );
lv_label_set_text(ui_Label13,"74");
lv_obj_set_style_text_font(ui_Label13, &ui_font_RowFont, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label14 = lv_label_create(ui_Panel3);
lv_obj_set_width( ui_Label14, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label14, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label14, 399 );
lv_obj_set_y( ui_Label14, 56 );
lv_obj_set_align( ui_Label14, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_Label14,"drag");
lv_obj_set_style_text_font(ui_Label14, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel4 = lv_obj_create(ui_RowScreen);
lv_obj_set_width( ui_Panel4, 534);
lv_obj_set_height( ui_Panel4, 50);
lv_obj_set_x( ui_Panel4, -1 );
lv_obj_set_y( ui_Panel4, -90 );
lv_obj_set_align( ui_Panel4, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelBatteryLifeRow = lv_label_create(ui_Panel4);
lv_obj_set_width( ui_LabelBatteryLifeRow, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelBatteryLifeRow, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelBatteryLifeRow, -7 );
lv_obj_set_y( ui_LabelBatteryLifeRow, -1 );
lv_obj_set_align( ui_LabelBatteryLifeRow, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_LabelBatteryLifeRow,"89%");
lv_obj_set_style_text_font(ui_LabelBatteryLifeRow, &lv_font_montserrat_44, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label8 = lv_label_create(ui_Panel4);
lv_obj_set_width( ui_Label8, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label8, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label8, LV_ALIGN_RIGHT_MID );
lv_label_set_text(ui_Label8,"ROWING MODE");
lv_obj_set_style_text_color(ui_Label8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label8, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label8, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_RowScreen, ui_event_RowScreen, LV_EVENT_ALL, NULL);

}
