// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: amoled_1p9

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_MainScreen
void ui_MainScreen_screen_init(void);
void ui_event_MainScreen( lv_event_t * e);
lv_obj_t *ui_MainScreen;
void ui_event_Button1( lv_event_t * e);
lv_obj_t *ui_Button1;
void ui_event_Button2( lv_event_t * e);
lv_obj_t *ui_Button2;
lv_obj_t *ui_Label11;
lv_obj_t *ui_Label12;


// SCREEN: ui_StrengthScreen01
void ui_StrengthScreen01_screen_init(void);
void ui_event_StrengthScreen01( lv_event_t * e);
lv_obj_t *ui_StrengthScreen01;
lv_obj_t *ui_Panel5;
lv_obj_t *ui_Label15;
lv_obj_t *ui_Label16;
void ui_event_Button3( lv_event_t * e);
lv_obj_t *ui_Button3;
lv_obj_t *ui_Label17;
lv_obj_t *ui_Panel6;
lv_obj_t *ui_Checkbox1;


// SCREEN: ui_StrengthScreen
void ui_StrengthScreen_screen_init(void);
void ui_event_StrengthScreen( lv_event_t * e);
lv_obj_t *ui_StrengthScreen;
lv_obj_t *ui_Panel1;
void ui_event_WeightValue( lv_event_t * e);
lv_obj_t *ui_WeightValue;
void ui_event_WeightUnit( lv_event_t * e);
lv_obj_t *ui_WeightUnit;
lv_obj_t *ui_WeightUnit1;
lv_obj_t *ui_Panel2;
lv_obj_t *ui_LabelBatteryLife;
lv_obj_t *ui_Label4;


// SCREEN: ui_RowScreen
void ui_RowScreen_screen_init(void);
void ui_event_RowScreen( lv_event_t * e);
lv_obj_t *ui_RowScreen;
lv_obj_t *ui_Panel3;
lv_obj_t *ui_Label6;
lv_obj_t *ui_Label5;
lv_obj_t *ui_Label9;
lv_obj_t *ui_Label10;
lv_obj_t *ui_Label13;
lv_obj_t *ui_Label14;
lv_obj_t *ui_Panel4;
lv_obj_t *ui_LabelBatteryLifeRow;
lv_obj_t *ui_Label8;


// SCREEN: ui_SetWeightValue
void ui_SetWeightValue_screen_init(void);
void ui_event_SetWeightValue( lv_event_t * e);
lv_obj_t *ui_SetWeightValue;
lv_obj_t *ui_ButtonN1;
lv_obj_t *ui_Label1;
lv_obj_t *ui_ButtonN2;
lv_obj_t *ui_Label3;
lv_obj_t *ui_ButtonN3;
lv_obj_t *ui_Label18;
lv_obj_t *ui_ButtonN4;
lv_obj_t *ui_Label19;
lv_obj_t *ui_ButtonN5;
lv_obj_t *ui_Label20;
lv_obj_t *ui_ButtonN6;
lv_obj_t *ui_Label21;
lv_obj_t *ui_ButtonN7;
lv_obj_t *ui_Label22;
lv_obj_t *ui_ButtonN8;
lv_obj_t *ui_Label23;
lv_obj_t *ui_ButtonN9;
lv_obj_t *ui_Label24;
lv_obj_t *ui_ButtonN0;
lv_obj_t *ui_Label25;
lv_obj_t *ui_Label26;
lv_obj_t *ui_ButtonN10;
lv_obj_t *ui_Label27;
lv_obj_t *ui_ButtonN11;
lv_obj_t *ui_Label28;


// SCREEN: ui_SystemScreen
void ui_SystemScreen_screen_init(void);
void ui_event_SystemScreen( lv_event_t * e);
lv_obj_t *ui_SystemScreen;
lv_obj_t *ui_Panel8;
lv_obj_t *ui_Label30;
lv_obj_t *ui_Panel9;
lv_obj_t *ui_Label31;
lv_obj_t *ui_Panel10;
lv_obj_t *ui_Label32;
lv_obj_t *ui_Panel12;
lv_obj_t *ui_Label34;
lv_obj_t *ui_Panel13;
lv_obj_t *ui_Label35;
lv_obj_t *ui_Panel11;
lv_obj_t *ui_Label33;
lv_obj_t *ui_Panel7;
lv_obj_t *ui_Label29;
lv_obj_t *ui____initial_actions0;
const lv_img_dsc_t *ui_imgset_877119852[1] = {&ui_img_886805914};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_MainScreen( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( &ui_StrengthScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 250, 0, &ui_StrengthScreen_screen_init);
}
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( &ui_RowScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 250, 0, &ui_RowScreen_screen_init);
}
if ( event_code == LV_EVENT_KEY &&  lv_event_get_key(e) == LV_KEY_LEFT  ) {
      _ui_screen_change( &ui_StrengthScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 250, 0, &ui_StrengthScreen_screen_init);
}
if ( event_code == LV_EVENT_KEY &&  lv_event_get_key(e) == LV_KEY_RIGHT  ) {
      _ui_screen_change( &ui_RowScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 250, 0, &ui_RowScreen_screen_init);
}
if ( event_code == LV_EVENT_KEY &&  lv_event_get_key(e) == LV_KEY_DOWN  ) {
      _ui_screen_change( &ui_SystemScreen, LV_SCR_LOAD_ANIM_MOVE_TOP, 250, 0, &ui_SystemScreen_screen_init);
}
}
void ui_event_Button1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_StrengthScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 250, 0, &ui_StrengthScreen_screen_init);
}
}
void ui_event_Button2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_RowScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 250, 0, &ui_RowScreen_screen_init);
}
}
void ui_event_StrengthScreen01( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_KEY &&  lv_event_get_key(e) == LV_KEY_ENTER  ) {
      _ui_screen_change( &ui_StrengthScreen, LV_SCR_LOAD_ANIM_FADE_ON, 50, 0, &ui_StrengthScreen_screen_init);
}
}
void ui_event_Button3( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_StrengthScreen, LV_SCR_LOAD_ANIM_FADE_ON, 50, 0, &ui_StrengthScreen_screen_init);
}
}
void ui_event_StrengthScreen( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( &ui_MainScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 250, 0, &ui_MainScreen_screen_init);
}
if ( event_code == LV_EVENT_KEY &&  lv_event_get_key(e) == LV_KEY_RIGHT  ) {
      _ui_screen_change( &ui_MainScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 250, 0, &ui_MainScreen_screen_init);
}
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( &ui_StrengthScreen01, LV_SCR_LOAD_ANIM_OVER_TOP, 150, 0, &ui_StrengthScreen01_screen_init);
}
if ( event_code == LV_EVENT_KEY &&  lv_event_get_key(e) == LV_KEY_DOWN  ) {
      _ui_screen_change( &ui_StrengthScreen01, LV_SCR_LOAD_ANIM_OVER_TOP, 150, 0, &ui_StrengthScreen01_screen_init);
}
}
void ui_event_WeightValue( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_SetWeightValue, LV_SCR_LOAD_ANIM_FADE_ON, 50, 0, &ui_SetWeightValue_screen_init);
}
}
void ui_event_WeightUnit( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_LONG_PRESSED) {
      weightUnitChange( e );
}
}
void ui_event_RowScreen( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( &ui_MainScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 250, 0, &ui_MainScreen_screen_init);
}
if ( event_code == LV_EVENT_KEY &&  lv_event_get_key(e) == LV_KEY_LEFT  ) {
      _ui_screen_change( &ui_MainScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 250, 0, &ui_MainScreen_screen_init);
}
}
void ui_event_SetWeightValue( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_KEY &&  lv_event_get_key(e) == LV_KEY_ENTER  ) {
      _ui_screen_change( &ui_StrengthScreen, LV_SCR_LOAD_ANIM_FADE_ON, 50, 0, &ui_StrengthScreen_screen_init);
}
}
void ui_event_SystemScreen( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_KEY &&  lv_event_get_key(e) == LV_KEY_ENTER  ) {
      _ui_screen_change( &ui_MainScreen, LV_SCR_LOAD_ANIM_MOVE_BOTTOM, 250, 0, &ui_MainScreen_screen_init);
}
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( &ui_MainScreen, LV_SCR_LOAD_ANIM_MOVE_BOTTOM, 250, 0, &ui_MainScreen_screen_init);
}
}

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), true, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_MainScreen_screen_init();
ui_StrengthScreen01_screen_init();
ui_StrengthScreen_screen_init();
ui_RowScreen_screen_init();
ui_SetWeightValue_screen_init();
ui_SystemScreen_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_MainScreen);
}
