// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: amoled_1p9

#ifndef _AMOLED_1P9_UI_H
#define _AMOLED_1P9_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_MainScreen
void ui_MainScreen_screen_init(void);
void ui_event_MainScreen( lv_event_t * e);
extern lv_obj_t *ui_MainScreen;
void ui_event_Button1( lv_event_t * e);
extern lv_obj_t *ui_Button1;
void ui_event_Button2( lv_event_t * e);
extern lv_obj_t *ui_Button2;
extern lv_obj_t *ui_Label11;
extern lv_obj_t *ui_Label12;
// SCREEN: ui_StrengthScreen01
void ui_StrengthScreen01_screen_init(void);
void ui_event_StrengthScreen01( lv_event_t * e);
extern lv_obj_t *ui_StrengthScreen01;
extern lv_obj_t *ui_Panel5;
extern lv_obj_t *ui_Label15;
extern lv_obj_t *ui_Label16;
void ui_event_Button3( lv_event_t * e);
extern lv_obj_t *ui_Button3;
extern lv_obj_t *ui_Label17;
extern lv_obj_t *ui_Panel6;
extern lv_obj_t *ui_Checkbox1;
// SCREEN: ui_StrengthScreen
void ui_StrengthScreen_screen_init(void);
void ui_event_StrengthScreen( lv_event_t * e);
extern lv_obj_t *ui_StrengthScreen;
extern lv_obj_t *ui_Panel1;
void ui_event_WeightValue( lv_event_t * e);
extern lv_obj_t *ui_WeightValue;
void ui_event_WeightUnit( lv_event_t * e);
extern lv_obj_t *ui_WeightUnit;
extern lv_obj_t *ui_WeightUnit1;
extern lv_obj_t *ui_Panel2;
extern lv_obj_t *ui_LabelBatteryLife;
extern lv_obj_t *ui_Label4;
// SCREEN: ui_RowScreen
void ui_RowScreen_screen_init(void);
void ui_event_RowScreen( lv_event_t * e);
extern lv_obj_t *ui_RowScreen;
extern lv_obj_t *ui_Panel3;
extern lv_obj_t *ui_Label6;
extern lv_obj_t *ui_Label5;
extern lv_obj_t *ui_Label9;
extern lv_obj_t *ui_Label10;
extern lv_obj_t *ui_Label13;
extern lv_obj_t *ui_Label14;
extern lv_obj_t *ui_Panel4;
extern lv_obj_t *ui_LabelBatteryLifeRow;
extern lv_obj_t *ui_Label8;
// SCREEN: ui_SetWeightValue
void ui_SetWeightValue_screen_init(void);
void ui_event_SetWeightValue( lv_event_t * e);
extern lv_obj_t *ui_SetWeightValue;
extern lv_obj_t *ui_ButtonN1;
extern lv_obj_t *ui_Label1;
extern lv_obj_t *ui_ButtonN2;
extern lv_obj_t *ui_Label3;
extern lv_obj_t *ui_ButtonN3;
extern lv_obj_t *ui_Label18;
extern lv_obj_t *ui_ButtonN4;
extern lv_obj_t *ui_Label19;
extern lv_obj_t *ui_ButtonN5;
extern lv_obj_t *ui_Label20;
extern lv_obj_t *ui_ButtonN6;
extern lv_obj_t *ui_Label21;
extern lv_obj_t *ui_ButtonN7;
extern lv_obj_t *ui_Label22;
extern lv_obj_t *ui_ButtonN8;
extern lv_obj_t *ui_Label23;
extern lv_obj_t *ui_ButtonN9;
extern lv_obj_t *ui_Label24;
extern lv_obj_t *ui_ButtonN0;
extern lv_obj_t *ui_Label25;
extern lv_obj_t *ui_Label26;
extern lv_obj_t *ui_ButtonN10;
extern lv_obj_t *ui_Label27;
extern lv_obj_t *ui_ButtonN11;
extern lv_obj_t *ui_Label28;
// SCREEN: ui_SystemScreen
void ui_SystemScreen_screen_init(void);
void ui_event_SystemScreen( lv_event_t * e);
extern lv_obj_t *ui_SystemScreen;
extern lv_obj_t *ui_Panel8;
extern lv_obj_t *ui_Label30;
extern lv_obj_t *ui_Panel9;
extern lv_obj_t *ui_Label31;
extern lv_obj_t *ui_Panel10;
extern lv_obj_t *ui_Label32;
extern lv_obj_t *ui_Panel12;
extern lv_obj_t *ui_Label34;
extern lv_obj_t *ui_Panel13;
extern lv_obj_t *ui_Label35;
extern lv_obj_t *ui_Panel11;
extern lv_obj_t *ui_Label33;
extern lv_obj_t *ui_Panel7;
extern lv_obj_t *ui_Label29;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( ui_img_886805914);   // assets\battery-6785506_640.png

LV_FONT_DECLARE( ui_font_RowFont);
LV_FONT_DECLARE( ui_font_RowFont2);
LV_FONT_DECLARE( ui_font_WeightFont);
LV_FONT_DECLARE( ui_font_WeightFont2);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
