// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: amoled_1p9

#ifndef UI_ROWSCREEN_H
#define UI_ROWSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_RowScreen
extern void ui_RowScreen_screen_init(void);
extern void ui_RowScreen_screen_destroy(void);
extern void ui_event_RowScreen(lv_event_t * e);
extern lv_obj_t * ui_RowScreen;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_LabelBatteryLife3;
extern lv_obj_t * ui_Label8;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

