// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: amoled_1p9

#ifndef UI_MAINSCREEN_H
#define UI_MAINSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_MainScreen
extern void ui_MainScreen_screen_init(void);
extern void ui_MainScreen_screen_destroy(void);
extern void ui_event_MainScreen(lv_event_t * e);
extern lv_obj_t * ui_MainScreen;
extern void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_LabelBatteryLife2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

