// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: amoled_1p9

#include "../ui.h"

lv_obj_t * ui_SystemScreen = NULL;
lv_obj_t * ui_Panel8 = NULL;
lv_obj_t * ui_Label30 = NULL;
lv_obj_t * ui_Panel9 = NULL;
lv_obj_t * ui_Label31 = NULL;
lv_obj_t * ui_Panel10 = NULL;
lv_obj_t * ui_Label32 = NULL;
lv_obj_t * ui_Panel11 = NULL;
lv_obj_t * ui_Label33 = NULL;
// event funtions
void ui_event_SystemScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_KEY &&  lv_event_get_key(e) == LV_KEY_ENTER) {
        _ui_screen_change(&ui_MainScreen, LV_SCR_LOAD_ANIM_MOVE_BOTTOM, 250, 0, &ui_MainScreen_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_MainScreen, LV_SCR_LOAD_ANIM_MOVE_BOTTOM, 250, 0, &ui_MainScreen_screen_init);
    }
    if(event_code == LV_EVENT_KEY &&  lv_event_get_key(e) == LV_KEY_LEFT) {
        _ui_screen_change(&ui_MainScreen, LV_SCR_LOAD_ANIM_MOVE_BOTTOM, 250, 0, &ui_MainScreen_screen_init);
    }
}

// build funtions

void ui_SystemScreen_screen_init(void)
{
    ui_SystemScreen = lv_obj_create(NULL);
    lv_obj_set_flex_flow(ui_SystemScreen, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_SystemScreen, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_set_style_bg_color(ui_SystemScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SystemScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_SystemScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_SystemScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_SystemScreen, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_SystemScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_SystemScreen, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_SystemScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel8 = lv_obj_create(ui_SystemScreen);
    lv_obj_set_height(ui_Panel8, 50);
    lv_obj_set_width(ui_Panel8, lv_pct(99));
    lv_obj_set_x(ui_Panel8, -174);
    lv_obj_set_y(ui_Panel8, -74);
    lv_obj_set_align(ui_Panel8, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel8, lv_color_hex(0x00265D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Panel8, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label30 = lv_label_create(ui_Panel8);
    lv_obj_set_width(ui_Label30, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label30, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label30, -1);
    lv_obj_set_y(ui_Label30, -1);
    lv_obj_set_align(ui_Label30, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label30, "Language");

    ui_Panel9 = lv_obj_create(ui_SystemScreen);
    lv_obj_set_height(ui_Panel9, 50);
    lv_obj_set_width(ui_Panel9, lv_pct(99));
    lv_obj_set_x(ui_Panel9, -174);
    lv_obj_set_y(ui_Panel9, -74);
    lv_obj_set_align(ui_Panel9, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel9, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Panel9, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label31 = lv_label_create(ui_Panel9);
    lv_obj_set_width(ui_Label31, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label31, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label31, -1);
    lv_obj_set_y(ui_Label31, -1);
    lv_obj_set_align(ui_Label31, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label31, "Usage Hours");

    ui_Panel10 = lv_obj_create(ui_SystemScreen);
    lv_obj_set_height(ui_Panel10, 50);
    lv_obj_set_width(ui_Panel10, lv_pct(99));
    lv_obj_set_x(ui_Panel10, -174);
    lv_obj_set_y(ui_Panel10, -74);
    lv_obj_set_align(ui_Panel10, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel10, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Panel10, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label32 = lv_label_create(ui_Panel10);
    lv_obj_set_width(ui_Label32, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label32, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label32, -1);
    lv_obj_set_y(ui_Label32, -1);
    lv_obj_set_align(ui_Label32, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label32, "Firmware version 0.0.1");

    ui_Panel11 = lv_obj_create(ui_SystemScreen);
    lv_obj_set_height(ui_Panel11, 50);
    lv_obj_set_width(ui_Panel11, lv_pct(99));
    lv_obj_set_x(ui_Panel11, -174);
    lv_obj_set_y(ui_Panel11, -74);
    lv_obj_set_align(ui_Panel11, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel11, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Panel11, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label33 = lv_label_create(ui_Panel11);
    lv_obj_set_width(ui_Label33, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label33, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label33, -1);
    lv_obj_set_y(ui_Label33, -1);
    lv_obj_set_align(ui_Label33, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label33, "Wireless Setup");

    lv_obj_add_event_cb(ui_SystemScreen, ui_event_SystemScreen, LV_EVENT_ALL, NULL);

}

void ui_SystemScreen_screen_destroy(void)
{
    if(ui_SystemScreen) lv_obj_del(ui_SystemScreen);

    // NULL screen variables
    ui_SystemScreen = NULL;
    ui_Panel8 = NULL;
    ui_Label30 = NULL;
    ui_Panel9 = NULL;
    ui_Label31 = NULL;
    ui_Panel10 = NULL;
    ui_Label32 = NULL;
    ui_Panel11 = NULL;
    ui_Label33 = NULL;

}
