// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: amoled_1p9

#include "../ui.h"

lv_obj_t * ui_StrengthScreen = NULL;
lv_obj_t * ui_Panel1 = NULL;
lv_obj_t * ui_WeightValue = NULL;
lv_obj_t * ui_WeightUnit = NULL;
lv_obj_t * ui_WeightUnit1 = NULL;
lv_obj_t * ui_Panel2 = NULL;
lv_obj_t * ui_LabelBatteryLife = NULL;
lv_obj_t * ui_Label4 = NULL;
// event funtions
void ui_event_StrengthScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_MainScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 250, 0, &ui_MainScreen_screen_init);
    }
    if(event_code == LV_EVENT_KEY &&  lv_event_get_key(e) == LV_KEY_RIGHT) {
        _ui_screen_change(&ui_MainScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 250, 0, &ui_MainScreen_screen_init);
    }
}

void ui_event_WeightUnit(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_LONG_PRESSED) {
        weightUnitChange(e);
    }
}

// build funtions

void ui_StrengthScreen_screen_init(void)
{
    ui_StrengthScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_StrengthScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel1 = lv_obj_create(ui_StrengthScreen);
    lv_obj_set_width(ui_Panel1, 533);
    lv_obj_set_height(ui_Panel1, 183);
    lv_obj_set_x(ui_Panel1, -1);
    lv_obj_set_y(ui_Panel1, 26);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WeightValue = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_WeightValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WeightValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WeightValue, -106);
    lv_obj_set_y(ui_WeightValue, 7);
    lv_obj_set_align(ui_WeightValue, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_WeightValue, "1");
    lv_obj_add_flag(ui_WeightValue, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_align(ui_WeightValue, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_WeightValue, &ui_font_WeightFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WeightUnit = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_WeightUnit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WeightUnit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WeightUnit, 399);
    lv_obj_set_y(ui_WeightUnit, -12);
    lv_obj_set_align(ui_WeightUnit, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_WeightUnit, "lb");
    lv_obj_add_flag(ui_WeightUnit, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_font(ui_WeightUnit, &ui_font_WeightFont2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WeightUnit1 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_WeightUnit1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WeightUnit1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WeightUnit1, 399);
    lv_obj_set_y(ui_WeightUnit1, 56);
    lv_obj_set_align(ui_WeightUnit1, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_WeightUnit1, "43%");
    lv_obj_add_flag(ui_WeightUnit1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_font(ui_WeightUnit1, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel2 = lv_obj_create(ui_StrengthScreen);
    lv_obj_set_width(ui_Panel2, 534);
    lv_obj_set_height(ui_Panel2, 50);
    lv_obj_set_x(ui_Panel2, -1);
    lv_obj_set_y(ui_Panel2, -90);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelBatteryLife = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_LabelBatteryLife, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelBatteryLife, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelBatteryLife, -7);
    lv_obj_set_y(ui_LabelBatteryLife, -1);
    lv_obj_set_align(ui_LabelBatteryLife, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_LabelBatteryLife, "89%");
    lv_obj_set_style_text_font(ui_LabelBatteryLife, &lv_font_montserrat_44, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label4, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_Label4, "STRENGTH MODE");
    lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_WeightUnit, ui_event_WeightUnit, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_StrengthScreen, ui_event_StrengthScreen, LV_EVENT_ALL, NULL);

}

void ui_StrengthScreen_screen_destroy(void)
{
    if(ui_StrengthScreen) lv_obj_del(ui_StrengthScreen);

    // NULL screen variables
    ui_StrengthScreen = NULL;
    ui_Panel1 = NULL;
    ui_WeightValue = NULL;
    ui_WeightUnit = NULL;
    ui_WeightUnit1 = NULL;
    ui_Panel2 = NULL;
    ui_LabelBatteryLife = NULL;
    ui_Label4 = NULL;

}
