// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: amoled_1p9

#ifndef UI_STRENGTHSCREEN_H
#define UI_STRENGTHSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_StrengthScreen
extern void ui_StrengthScreen_screen_init(void);
extern void ui_StrengthScreen_screen_destroy(void);
extern void ui_event_StrengthScreen(lv_event_t * e);
extern lv_obj_t * ui_StrengthScreen;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_WeightValue;
extern void ui_event_WeightUnit(lv_event_t * e);
extern lv_obj_t * ui_WeightUnit;
extern lv_obj_t * ui_WeightUnit1;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_LabelBatteryLife;
extern lv_obj_t * ui_Label4;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

