// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: amoled_1p9

#ifndef UI_SYSTEMSCREEN_H
#define UI_SYSTEMSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_SystemScreen
extern void ui_SystemScreen_screen_init(void);
extern void ui_SystemScreen_screen_destroy(void);
extern void ui_event_SystemScreen(lv_event_t * e);
extern lv_obj_t * ui_SystemScreen;
extern lv_obj_t * ui_Panel8;
extern lv_obj_t * ui_Label30;
extern lv_obj_t * ui_Panel9;
extern lv_obj_t * ui_Label31;
extern lv_obj_t * ui_Panel10;
extern lv_obj_t * ui_Label32;
extern lv_obj_t * ui_Panel11;
extern lv_obj_t * ui_Label33;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

